version: "3.5"

networks:
  dbnet:
    external: true
    name: dbnet

services:
  queue-web:
    image: webdevops/php-apache:7.3
    volumes:
    - ./:/app/
    ports:
    - "8999:80"
    environment:
      VIRTUAL_HOST: queue.mike
      PHP_OPCACHE_MEMORY_CONSUMPTION: 192
      PHP_OPCACHE_MAX_ACCELERATED_FILES: 10000
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      PHP_OPCACHE_REVALIDATE_FREQ: 0
      PHP_OPCACHE_INTERNED_STRINGS_BUFFER: 16
    stdin_open: true
    tty: true
    depends_on:
      - queue-database
    networks:
      - dbnet

  queue-server:
    image: webdevops/php-apache:7.3
    command: php /app/server.php
    volumes:
    - ./:/app/
    environment:
      PHP_OPCACHE_MEMORY_CONSUMPTION: 192
    stdin_open: true
    tty: true
    depends_on:
      - queue-database
    networks:
      - dbnet

  queue-database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: queue
      MYSQL_DATABASE: queue
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION
    tmpfs:
      - /var/lib/mysql:rw
    volumes:
      - ./assets/database/queueserver.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    networks:
      - dbnet